version: "3.9"

services:
  backend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: java -jar app.jar #java -classpath src ru.app.Main
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_SERVER: mysql_db
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - "30000:8080"
    depends_on:
      - mysql_db